//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using MyTasks.Domain.Base;

namespace MyTasks.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category: BaseObject
    {
        public Category()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
