//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MyTasks.Domain.Base;
using MyTasks.Localization.Desktop;

namespace MyTasks.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer: BaseObject
    {
        public Customer()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int CustomerId { get; set; }
        [Required(ErrorMessageResourceType = typeof(Desktop), ErrorMessageResourceName = "CustomerNameIsRequired")]
        public string Name { get; set; }
        public string MainContactName { get; set; }

        [EmailAddress(ErrorMessageResourceType = typeof(Desktop), ErrorMessageResourceName = "EmailAddressNotValid")]
        public string MainContactEmail { get; set; }

        [NotMapped]
        public bool IsUsed { get; set; }

        [NotMapped]
        public string UsedCaption { get; set; }


        public virtual ICollection<Project> Projects { get; set; }
    }
}
