//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MyTasks.Domain.Base;

namespace MyTasks.Domain
{
    using System;
    using System.Collections.Generic;

    public partial class Priority : BaseObject
    {
        public Priority()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int PriorityId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }

        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
