//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;
using FluentValidation.Attributes;
using MyTasks.Domain.Base;
using MyTasks.Domain.Entities.Validators;

namespace MyTasks.Domain
{
    using System;
    using System.Collections.Generic;

    [Validator(typeof(ProjectValidator))]
    public partial class Project : BaseObject
    {
        public Project()
        {
            this.Tickets = new HashSet<Ticket>();
            this.Areas = new HashSet<Area>();
        }
    
        public int ProjectId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public string ProjectManagerId { get; set; }
        
        [NotMapped]
        public bool IsUsed { get; set; }

        [NotMapped]
        public string UsedCaption { get; set; }

        public virtual Customer customer { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<Area> Areas { get; set; }
    }
}
