//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MyTasks.Domain.Base;

namespace MyTasks.Domain
{
    using System;
    using System.Collections.Generic;

    public partial class Roles : BaseObject
    {
        public Roles()
        {
            this.users = new HashSet<Users>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Users> users { get; set; }
    }
}
