//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MyTasks.Domain.Base;
using MyTasks.Domain.Entities;

namespace MyTasks.Domain
{
    using System;
    using System.Collections.Generic;

    public partial class Ticket : BaseObject
    {
        public Ticket()
        {
            this.workingon = new HashSet<WorkingOn>();
            Files= new HashSet<FileData>();
        }
    
        public int TicketDetailId { get; set; }
        public int? TicketNumber { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> TicketStatusId { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsHtml { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string OwnerUserId { get; set; }
        public string AssignedTo { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }

        public bool HasFiles { get; set; }
        public int? ParentTicketId { get; set; }
        public bool EditionMarkAsDeleted { get; set; }
        public bool IsLastDetail { get; set; }
        public bool IsBillable { get; set; }
        public virtual Category Category { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<WorkingOn> workingon { get; set; }
        public virtual Area Area { get; set; }
        public virtual Ticketstatus Ticketstatus { get; set; }

        public virtual ICollection<FileData> Files { get; set; }

        public void UpdateTicketNumber()
        {
            TicketNumber = TicketDetailId;
        }

    }
}

