//----------------------------------------------------------------------------------------
//	Copyright © 2003 - 2013 Tangible Software Solutions Inc.
//	This class can be used by anyone provided that the copyright notice remains intact.
//
//	This file simulates the behavior of VB's My.Application when the original VB project
//	did not include an autogenerated My.Application class.
//----------------------------------------------------------------------------------------

namespace My
{
	internal partial class MyApplication : Microsoft.VisualBasic.ApplicationServices.ApplicationBase
	{
		[global::System.Diagnostics.DebuggerStepThroughAttribute()]
		public MyApplication() : base()
		{
		}

		private static MyApplication MyApp;
		internal static MyApplication Application
		{
			get
			{
				if (MyApp == null)
					MyApp = new MyApplication();

				return MyApp;
			}
		}
	}
}