//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTasks.Localization.ClientSide {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientSide {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientSide() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyTasks.Localization.ClientSide.ClientSide", typeof(ClientSide).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is required.
        /// </summary>
        public static string CustomerIsRequired {
            get {
                return ResourceManager.GetString("CustomerIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entry in area list..
        /// </summary>
        public static string InvalidAreaInList {
            get {
                return ResourceManager.GetString("InvalidAreaInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 area is required..
        /// </summary>
        public static string OnAreaIsRequired {
            get {
                return ResourceManager.GetString("OnAreaIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project manager is required.
        /// </summary>
        public static string ProjectManagerIsRequired {
            get {
                return ResourceManager.GetString("ProjectManagerIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name is required.
        /// </summary>
        public static string ProjectNameIsRequired {
            get {
                return ResourceManager.GetString("ProjectNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resoled.
        /// </summary>
        public static string Resoled {
            get {
                return ResourceManager.GetString("Resoled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an area.
        /// </summary>
        public static string SelectAnArea {
            get {
                return ResourceManager.GetString("SelectAnArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category to filter:.
        /// </summary>
        public static string SelectCategoryToFilter {
            get {
                return ResourceManager.GetString("SelectCategoryToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select priority to filter:.
        /// </summary>
        public static string SelectPriorityToFilter {
            get {
                return ResourceManager.GetString("SelectPriorityToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select project to filter:.
        /// </summary>
        public static string SelectProjectToFilter {
            get {
                return ResourceManager.GetString("SelectProjectToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select status to filter:.
        /// </summary>
        public static string SelectStatusToFilter {
            get {
                return ResourceManager.GetString("SelectStatusToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary by project.
        /// </summary>
        public static string SummaryByProject {
            get {
                return ResourceManager.GetString("SummaryByProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary by user.
        /// </summary>
        public static string SummaryByUser {
            get {
                return ResourceManager.GetString("SummaryByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save changes. Try again, and if the problem persists, see your system administrator..
        /// </summary>
        public static string UnableToSaveChanges {
            get {
                return ResourceManager.GetString("UnableToSaveChanges", resourceCulture);
            }
        }
    }
}
